Areas/MST_Student/Controllers/Mst_StudentController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using database.Areas.Loc_State.Models;
using database.Areas.MST_Student.Models;
using database.Areas.Loc_Country.Models;
using database.Areas.Loc_City.Models;
using database.Areas.MST_Branch.Models;
using Microsoft.CodeAnalysis.Operations;
using System.Xml.Linq;
using System.Security.Cryptography.X509Certificates;

namespace database.Areas.MST_Student.Controllers
{
    [Area("MST_Student")]
    [Route("MST_Student/[controller]/[action]")]
    public class Mst_StudentController : Controller
    {
        private IConfiguration configuration;

        #region con
        public Mst_StudentController(IConfiguration configuration)
        {
            this.configuration = configuration;
        }
        #endregion
        public IActionResult Index()
        {
            FillBranchDDL();
            FillCityDDL();
            String ConnString = this.configuration.GetConnectionString("Mystring");
            DataTable dt = new DataTable();
            SqlConnection sqlConn = new SqlConnection(ConnString);
            sqlConn.Open();
            SqlCommand cmd = sqlConn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "Pro_Student_select";
            SqlDataReader reader = cmd.ExecuteReader();
            dt.Load(reader);
            return View("Mst_StudentList",dt);
        }
        public IActionResult Mst_StudentDelete(int StudentID)
        {
            try
            {
                String ConnString = this.configuration.GetConnectionString("Mystring");
                DataTable dt = new DataTable();
                SqlConnection sqlConn = new SqlConnection(ConnString);
                /* SqlDatabase db=new SqlDatabase(ConnString);*/
                sqlConn.Open();
                SqlCommand cmd = sqlConn.CreateCommand();
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.CommandText = "Pro_Student_delete";
                cmd.Parameters.AddWithValue("@StudentID", StudentID);
                SqlDataReader reader = cmd.ExecuteReader();
                dt.Load(reader);
                sqlConn.Close();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }

        public IActionResult Mst_StudentAddEdit(int? StudentID)
        {
            FillCityDDL();
            FillBranchDDL();
            if (StudentID != null)
            {
                String ConnString = this.configuration.GetConnectionString("Mystring");
                DataTable dt = new DataTable();
                SqlConnection sqlConn = new SqlConnection(ConnString);
                /* SqlDatabase db=new SqlDatabase(ConnString);*/
                sqlConn.Open();
                SqlCommand cmd = sqlConn.CreateCommand();
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.CommandText = "Pro_Student_selectByPk";
                cmd.Parameters.Add("@StudentID", SqlDbType.Int).Value = StudentID;
                SqlDataReader objSDR = cmd.ExecuteReader();
                dt.Load(objSDR);

                Mst_Student modelStudent = new Mst_Student();
                foreach (DataRow dr in dt.Rows)
                {
                    modelStudent.StudentID = Convert.ToInt32(dr["StudentID"]);
                    modelStudent.StudentName = dr["StudentName"].ToString();
                    modelStudent.CityID = Convert.ToInt32(dr["CityID"].ToString());
                    modelStudent.BranchID = Convert.ToInt32(dr["BranchID"].ToString());
                    modelStudent.MobileNoStudent = dr["MobileNoStudent"].ToString();
                    modelStudent.Email = dr["Email"].ToString();
                    modelStudent.MobileNoFather = dr["MobileNoFather"].ToString();
                    modelStudent.Address = dr["Address"].ToString();
                    modelStudent.BirthDate =Convert.ToDateTime(dr["BirthDate"]);
                    modelStudent.Age = Convert.ToInt32(dr["Age"].ToString());
                    modelStudent.IsActive =Convert.ToBoolean(dr["IsActive"]);
                    modelStudent.Gender = dr["Gender"].ToString();
                    modelStudent.Password = dr["Password"].ToString();
                 
                }
                return View("Mst_StudentAddEdit", modelStudent);

            }
            return View();
        }

        public IActionResult Save(Mst_Student modelStudent)
        {
            String ConnString = this.configuration.GetConnectionString("Mystring");
            DataTable dt = new DataTable();
            SqlConnection sqlConn = new SqlConnection(ConnString);
            sqlConn.Open();
            SqlCommand cmd = sqlConn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            if (modelStudent.StudentID == null)
            {
                cmd.CommandText = "Pro_Student_insert";
                //cmd.Parameters.Add("@CountryAddDate", SqlDbType.DateTime).Value = DBNull.Value;
            }
            else
            {
                cmd.CommandText = "Pro_Student_update";
                cmd.Parameters.Add("@StudentID", SqlDbType.Int).Value = modelStudent.StudentID;

            }
            cmd.Parameters.Add("@StudentName", SqlDbType.VarChar).Value = modelStudent.StudentName;
            cmd.Parameters.Add("@CityID", SqlDbType.Int).Value = modelStudent.CityID;
            cmd.Parameters.Add("@BranchID", SqlDbType.Int).Value = modelStudent.BranchID;
            cmd.Parameters.Add("@MobileNoStudent", SqlDbType.VarChar).Value = modelStudent.MobileNoStudent;
            cmd.Parameters.Add("@Email", SqlDbType.VarChar).Value = modelStudent.Email;
            cmd.Parameters.Add("@MobileNoFather", SqlDbType.VarChar).Value = modelStudent.MobileNoFather;
            cmd.Parameters.Add("@Address", SqlDbType.VarChar).Value = modelStudent.Address;
            cmd.Parameters.Add("@BirthDate", SqlDbType.DateTime).Value = Convert.ToDateTime(modelStudent.BirthDate);
            cmd.Parameters.Add("@Age", SqlDbType.Int).Value = modelStudent.Age;
            cmd.Parameters.Add("@IsActive", SqlDbType.Bit).Value = modelStudent.IsActive;
            cmd.Parameters.Add("@Gender", SqlDbType.VarChar).Value = modelStudent.Gender;
            cmd.Parameters.Add("@Password", SqlDbType.VarChar).Value = modelStudent.Password;
            if (Convert.ToBoolean(cmd.ExecuteNonQuery()))
            {
                if (modelStudent.StudentID == null)
                {
                    TempData["StateInsertMsg"] = "Record Inserted Successfully";
                }
                else
                {
                    TempData["StateInsertMsg"] = "Record updated Successfully";
                }
            }
            sqlConn.Close();
            return RedirectToAction("Index");
        }
        
        public void FillCityDDL()
        {

            String ConnString = this.configuration.GetConnectionString("Mystring");
            List<LOC_CityDropDownModel> loc_City = new
           List<LOC_CityDropDownModel>();
            SqlConnection objConn = new SqlConnection(ConnString);
            objConn.Open();
            SqlCommand objCmd = objConn.CreateCommand();
            objCmd.CommandType = CommandType.StoredProcedure;
            objCmd.CommandText = "PR_City_SelectAll_Dropdown";
            SqlDataReader objSDR = objCmd.ExecuteReader();
            if (objSDR.HasRows)
            {
                while (objSDR.Read())
                {
                    LOC_CityDropDownModel city = new
               LOC_CityDropDownModel()
                    {
                        CityID = Convert.ToInt32(objSDR["CityID"]),
                        CityName = objSDR["CityName"].ToString()
                    };
                    loc_City.Add(city);
                }
                objSDR.Close();
            }
            objConn.Close();
            ViewBag.CityList = loc_City;

        }
        public void FillBranchDDL()
        {

            String ConnString = this.configuration.GetConnectionString("Mystring");
            List<Mst_BranchDropDownModel> Mst_branch = new
           List<Mst_BranchDropDownModel>();
            SqlConnection objConn = new SqlConnection(ConnString);
            objConn.Open();
            SqlCommand objCmd = objConn.CreateCommand();
            objCmd.CommandType = CommandType.StoredProcedure;
            objCmd.CommandText = "PR_Branch_SelectAll_Dropdown";
            SqlDataReader objSDR = objCmd.ExecuteReader();
            if (objSDR.HasRows)
            {
                while (objSDR.Read())
                {
                    Mst_BranchDropDownModel branch = new
               Mst_BranchDropDownModel()
                    {
                        BranchID = Convert.ToInt32(objSDR["BranchID"]),
                        BranchName = objSDR["BranchName"].ToString()
                    };
                    Mst_branch.Add(branch);
                }
                objSDR.Close();
            }
            objConn.Close();
            ViewBag.branchList = Mst_branch;

        

        }


        private DataTable _fetchData(String? StudentName, String? Email, String? Address, String? Age, String? Gender, int BranchID = -1, int CityID = -1)
        {
            String ConnString = this.configuration.GetConnectionString("Mystring");
            DataTable dt = new DataTable();
            SqlConnection sqlConn = new SqlConnection(ConnString);
            sqlConn.Open();
            SqlCommand cmd = sqlConn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "Pro_Student_select";
            if(StudentName!="") cmd.Parameters.Add("@StudentName", SqlDbType.NVarChar).Value = StudentName;

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>@ViewData["Title"] - database</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: NiceAdmin
    * Updated: May 30 2023 with Bootstrap v5.3.0
    * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a href="index.html" class="logo d-flex align-items-center">
                <img src="~/assets/img/logo.png" alt="">
                <span class="d-none d-lg-block">Database</span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div><!-- End Logo -->

        <div class="search-bar">
            <form class="search-form d-flex align-items-center" method="POST" action="#">
                <input type="text" name="query" placeholder="Search" title="Enter search keyword">
                <button type="submit" title="Search"><i class="bi bi-search"></i></button>
            </form>
        </div>
        <!-- End Search Bar -->
        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">
                <li class="nav-item d-block d-lg-none">
                    <a class="nav-link nav-icon search-bar-toggle " href="#">
                        <i class="bi bi-search"></i>
                    </a>
                </li>
                <!-- End Search Icon-->
            </ul>
        </nav><!-- End Icons Navigation -->

    </header>
    <!-- End Header -->

    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="home">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <!-- End Dashboard Nav -->


            <!-- Start Country Nav-->
            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#Table-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-menu-button-wide"></i><span>Tables</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="Table-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a asp-area="Loc_Country" asp-action="Index" asp-controller="Loc_Country">
                            <i class="bi bi-circle"></i><span>Country</span>
                        </a>
                    </li>
                    <li>
                        <a asp-area="Loc_State" asp-action="Index" asp-controller="Loc_State">
                            <i class="bi bi-circle"></i><span>State</span>
                        </a>
                    </li>
                    <li>
                        <a asp-area="Loc_City" asp-action="Index" asp-controller="Loc_City">
                            <i class="bi bi-circle"></i><span>City</span>
                        </a>
                    </li>
                    <li>
                        <a asp-area="MST_Branch" asp-action="Index" asp-controller="MST_Branch">
                            <i class="bi bi-circle"></i><span>Branch</span>
                        </a>
                    </li>
                    <li>
                        <a asp-area="MST_Student" asp-action="Index" asp-controller="Mst_Student">
                            <i class="bi bi-circle"></i><span>Student</span>
                        </a>
                    </li>

                </ul>
            </li>
            <!-- End Country Nav -->

           @*  <!-- Start State Nav-->
            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#State-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-menu-button-wide"></i><span>State</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="State-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a asp-area="Loc_State" asp-action="Loc_StateAddedit" asp-controller="Loc_State">
                            <i class="bi bi-circle"></i><span>Add State</span>
                        </a>
                    </li>
                    <li>
                        <a asp-area="Loc_State" asp-action="Index" asp-controller="Loc_State">
                            <i class="bi bi-circle"></i><span>State List</span>
                        </a>
                    </li>
                    <li>
                        <a asp-area="Loc_City" asp-action="Index" asp-controller="Loc_City">
                            <i class="bi bi-circle"></i><span>City List</span>
                        </a>
                    </li>
                </ul>
            </li>
            <!-- End State Nav -->

            <!-- Start City Nav-->
            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#City-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-menu-button-wide"></i><span>City</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="City-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a asp-area="Loc_City" asp-action="Loc_CityAddedit" asp-controller="Loc_City">
                            <i class="bi bi-circle"></i><span>Add City</span>
                        </a>
                    </li>
                  
                </ul>
            </li>
            <!-- End City Nav -->

            <!-- Start Branch Nav-->
            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#Branch-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-menu-button-wide"></i><span>Branch</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="Branch-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a asp-area="MST_Branch" asp-action="MST_BranchAddedit" asp-controller="MST_Branch">
                            <i class="bi bi-circle"></i><span>Add Branch</span>
                        </a>
                    </li>
                    <li>
                        <a asp-area="MST_Branch" asp-action="Index" asp-controller="MST_Branch">
                            <i class="bi bi-circle"></i><span>Branch List</span>
                        </a>
                    </li>
                </ul>
            </li>
            <!-- End Branch Nav -->

            <!-- Start Student Nav-->
            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#Student-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-menu-button-wide"></i><span>Student</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="Student-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a asp-area="MST_Student" asp-action="Mst_StudentAddEdit" asp-controller="Mst_Student">
                            <i class="bi bi-circle"></i><span>Add Student</span>
                        </a>
                    </li>
                    <li>
                        <a asp-area="MST_Student" asp-action="Index" asp-controller="Mst_Student">
                            <i class="bi bi-circle"></i><span>Student List</span>
                        </a>
                    </li>
                </ul>
            </li>
            <!-- End Student Nav --> *@

            
            <li class="nav-heading">Pages</li>

            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="" asp-controller="Home" asp-action="profile">
                    <i class="bi bi-person"></i>
                    <span>Profile</span>
                </a>
            </li><!-- End Profile Page Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="" asp-controller="Home" asp-action="Faq">
                    <i class="bi bi-question-circle"></i>
                    <span>F.A.Q</span>
                </a>
            </li><!-- End F.A.Q Page Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="" asp-controller="Home" asp-action="contact">
                    <i class="bi bi-envelope"></i>
                    <span>Contact</span>
                </a>
            </li><!-- End Contact Page Nav -->

          @*   <li class="nav-item">
                <a class="nav-link collapsed" href="pages-register.html">
                    <i class="bi bi-card-list"></i>
                    <span>Register</span>
                </a>
            </li><!-- End Register Page Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" href="pages-login.html">
                    <i class="bi bi-box-arrow-in-right"></i>
                    <span>Login</span>
                </a>
            </li><!-- End Login Page Nav --> *@

        </ul>
    </aside>

    <!-- End Sidebar-->

   

    <div>
        <main id="main" class="main">
            <section class="section dashboard">
            @RenderBody()
             </section>
        </main>
    </div>


    <!-- End #main -->
    
    <!-- ======= Footer ======= -->
    <footer id="footer" class="border-top footer">
        <div class="copyright">
            &copy; Copyright <strong><span>2023 - database</span></strong>.
        </div>
        
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
            @* esigned by <a href="https://bootstrapmade.com/">BootstrapMade</a> *@
            All Rights Reserved <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/chart.js/chart.umd.js"></script>
    <script src="~/assets/vendor/echarts/echarts.min.js"></script>
    <script src="~/assets/vendor/quill/quill.min.js"></script>
    <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>
@*  <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script> *@
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>